spring.application.name=url-shortener

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/short-url-db
spring.datasource.username=*****
spring.datasource.password=*****

spring.jpa.hibernate.ddl-auto=update

url.short.code.length=6
url.short.code.characters=0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
url.short.code.expiration.days=15
url.short.code.cleanup.interval.hours=1
